language: node_js
sudo: false

# Keep this in sync with appveyor.yml
node_js:
- '6'
- '7'

before_script:
# If this command fails and you can't fix it, file an issue and add an exception to .nsprc
- npm run nsp-check

# Keep this in sync with appveyor.yml
script:
- npm run lint
- npm test
